name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        # This `frozen: false` is a workaround for the fact that release-please
        # is not properly updating the lockfile for interdependencies. `npm ci`
        # is run by setup-tools by default (when frozen=true) but this command
        # will fail if more than one package has a version change. This is a bug
        # in release-please, which should be updating the version numbers in release PR.
        with:
          frozen: false

      - name: Run Prettier
        run: npm run prettier-check

      - name: Run Lint
        run: npm run lint

      - name: Build React SDK types
        run: npm -w @tambo-ai/react run build:cjs

      - name: Run Type Check
        run: npm run check-types

  test:
    runs-on: ubuntu-latest
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        # This `frozen: false` is a workaround for the fact that release-please
        # is not properly updating the lockfile for interdependencies. `npm ci`
        # is run by setup-tools by default (when frozen=true) but this command
        # will fail if more than one package has a version change. This is a bug
        # in release-please, which should be updating the version numbers in release PR.
        with:
          frozen: false

      - name: Run Tests
        id: test
        continue-on-error: true
        run: npm run test -- -- --coverage --coverageReporters=json-summary --coverageReporters=text

      - name: Upload coverage artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-${{ github.event.pull_request.number }}
          path: "**/coverage/coverage-summary.json"
          if-no-files-found: ignore

      - name: Cache coverage for base branch
        if: github.event_name == 'push'
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: "**/coverage/coverage-summary.json"
          key: coverage-${{ github.ref_name }}-${{ github.sha }}

      - name: Update latest base branch coverage cache
        if: github.event_name == 'push'
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: "**/coverage/coverage-summary.json"
          key: coverage-${{ github.ref_name }}-latest
          enableCrossOsArchive: true

      - name: Fail if tests failed
        if: steps.test.outcome == 'failure'
        run: exit 1

  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        # This `frozen: false` is a workaround for the fact that release-please
        # is not properly updating the lockfile for interdependencies. `npm ci`
        # is run by setup-tools by default (when frozen=true) but this command
        # will fail if more than one package has a version change. This is a bug
        # in release-please, which should be updating the version numbers in release PR.
        with:
          frozen: false

      - name: Run E2E Tests
        run: npm run test:e2e -w @tambo-ai-cloud/api

      - name: Build
        run: npm run build
        env:
          DATABASE_URL: "postgresql://dummy-user:dummy-password@dummy-host:5432/dummy-database"
          API_KEY_SECRET: "dummy-api-key-secret"
          PROVIDER_KEY_SECRET: "dummy-provider-key-secret"
          NEXTAUTH_SECRET: "dummy-nextauth-secret"
          NEXTAUTH_URL: "http://localhost:8260"
          SKIP_ENV_VALIDATION: "true"
