name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.1

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        # This `frozen: false` is a workaround for the fact that release-please
        # is not properly updating the lockfile for interdependencies. `npm ci`
        # is run by setup-tools by default (when frozen=true) but this command
        # will fail if more than one package has a version change. This is a bug
        # in release-please, which should be updating the version numbers in release PR.
        with:
          frozen: false

      - name: Run Prettier
        run: npm run prettier-check

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        # Have to use extra -- -- because of turbo wrapping
        run: npm run test -- -- --coverage

      - name: Run E2E Tests
        run: npm run test:e2e -w @tambo-ai-cloud/api

      - name: Build
        run: npm run build
        env:
          DATABASE_URL: "postgresql://dummy-user:dummy-password@dummy-host:5432/dummy-database"
          API_KEY_SECRET: "dummy-api-key-secret"
          PROVIDER_KEY_SECRET: "dummy-provider-key-secret"
          NEXTAUTH_SECRET: "dummy-nextauth-secret"
          NEXTAUTH_URL: "http://localhost:8260"
          SKIP_ENV_VALIDATION: "true"
